Neos:
  Neos:
    modules:
      management:
        submodules:
          history:
            controller: \AE\History\Controller\HistoryController
            privilegeTarget: 'AE.History:BackendModule'
            additionalResources:
              styleSheets:
                - 'resource://AE.History/Public/Styles/Module.css'

    userInterface:
      requireJsPathMapping:
        'AE.History/Views': 'resource://AE.History/Public/JavaScript'

  Flow:
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'AE.History:Controllers':
                pattern: 'ControllerObjectName'
                patternOptions:
                  controllerObjectNamePattern: 'AE\History\Controller\.*'